apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d1
  namespace: paper2
  labels:
    app: service-d
    version: service-d1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
      version: service-d1

  template:
    metadata:
      labels:
        app: service-d
        version: service-d1

    spec:
      containers:
      - name: service-d
        image: hokunpark/paper2:serviceD2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"  
        ports:
        - containerPort: 11003
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11003"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker1

