

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c1
  namespace: paper2
  labels:
    app: service-c
    version: service-c1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
      version: service-c1

  template:
    metadata:
      labels:
        app: service-c
        version: service-c1

    spec:
      containers:
      - name: service-c
        image: hokunpark/paper2:serviceC2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"  
        ports:
        - containerPort: 11002
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11002"]


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c2
  namespace: paper2
  labels:
    app: service-c
    version: service-c2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
      version: service-c2

  template:
    metadata:
      labels:
        app: service-c
        version: service-c2

    spec:
      containers:
      - name: service-c
        image: hokunpark/paper2:serviceC2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"  
        ports:
        - containerPort: 11002
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11002"]


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c3
  namespace: paper2
  labels:
    app: service-c
    version: service-c3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
      version: service-c3

  template:
    metadata:
      labels:
        app: service-c
        version: service-c3

    spec:
      containers:
      - name: service-c
        image: hokunpark/paper2:serviceC2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"  
        ports:
        - containerPort: 11002
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11002"]


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c4
  namespace: paper2
  labels:
    app: service-c
    version: service-c4

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
      version: service-c4

  template:
    metadata:
      labels:
        app: service-c
        version: service-c4

    spec:
      containers:
      - name: service-c
        image: hokunpark/paper2:serviceC2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "500Mi"  
        ports:
        - containerPort: 11002
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11002"]

