

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d1
  namespace: paper2
  labels:
    app: service-d
    version: service-d1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
      version: service-d1

  template:
    metadata:
      labels:
        app: service-d
        version: service-d1

    spec:
      containers:
      - name: service-d
        image: hokunpark/paper2:serviceD2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "400m"
            memory: "500Mi"
          limits:
            cpu: "400m"
            memory: "500Mi"  
        ports:
        - containerPort: 11003
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11003"]
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d2
  namespace: paper2
  labels:
    app: service-d
    version: service-d2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
      version: service-d2

  template:
    metadata:
      labels:
        app: service-d
        version: service-d2

    spec:
      containers:
      - name: service-d
        image: hokunpark/paper2:serviceD2
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "400m"
            memory: "500Mi"
          limits:
            cpu: "400m"
            memory: "500Mi"  
        ports:
        - containerPort: 11003
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11003"]
 

