apiVersion: v1
kind: Service
metadata:
  name: service-e
  namespace: paper2
spec:
  selector:
    app: service-e
  ports:
  - name: http
    port: 11004
    protocol: TCP
    targetPort: 11004
  type: ClusterIP
