apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: paper2
spec:
  selector:
    app: service-c
  ports:
  - name: http
    port: 11002
    protocol: TCP
    targetPort: 11002
  type: ClusterIP
