apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d2
  namespace: paper2
  labels:
    app: service-d
    version: service-d2
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
      version: service-d2
      
  template:
    metadata:
      labels:
        app: service-d
        version: service-d2
        
    spec:
      containers:
      - name: service-d
        image: hokunpark/paper2:serviceD
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        ports:
        - containerPort: 11003
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11003"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker2