apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: paper2
spec:
  selector:
    app: service-a
  ports:
  - name: http
    port: 11000
    protocol: TCP
    targetPort: 11000
  type: ClusterIP