
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b3
  namespace: paper2
  labels:
    app: service-b
    version: service-b3
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: service-b3
      
  template:
    metadata:
      labels:
        app: service-b
        version: service-b3
        
    spec:
      containers:
      - name: service-b
        image: hokunpark/paper2:serviceB
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        ports:
        - containerPort: 11001
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11001"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker3