apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: paper2
spec:
  selector:
    app: service-b
  ports:
  - name: http
    port: 11001
    protocol: TCP
    targetPort: 11001
  type: ClusterIP
