apiVersion: v1
kind: Service
metadata:
  name: service-d
  namespace: paper2
spec:
  selector:
    app: service-d
  ports:
  - name: http
    port: 11003
    protocol: TCP
    targetPort: 11003
  type: ClusterIP
