

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b1
  namespace: paper2
  labels:
    app: service-b
    version: service-b1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: service-b1

  template:
    metadata:
      labels:
        app: service-b
        version: service-b1

    spec:
      containers:
      - name: service-b
        image: hokunpark/paper2:serviceB2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"  
        ports:
        - containerPort: 11001
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11001"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b2
  namespace: paper2
  labels:
    app: service-b
    version: service-b2

spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
      version: service-b2

  template:
    metadata:
      labels:
        app: service-b
        version: service-b2

    spec:
      containers:
      - name: service-b
        image: hokunpark/paper2:serviceB2
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"  
        ports:
        - containerPort: 11001
        command: ["uvicorn"]
        args: ["main:app", "--host", "0.0.0.0", "--port", "11001"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker4
